services:
  frontend:
    image: myfrontend
    container_name: myfrontend
    build: .
    ports:
      - "8080:80"
    networks:
      - mynetwork
    env_file:
      - .env
networks:
  mynetwork:
    name: mynetwork